apiVersion: v1
kind: ConfigMap
metadata:
  name: retool-temporal-web-config
  labels:
    app.kubernetes.io/name: retool-temporal
    app.kubernetes.io/instance: retool
    app.kubernetes.io/component: web
data:
  config.yml: |
    auth:
      enabled: false
    routing:
      default_to_namespace: workflows
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: retool-temporal-web
  labels:
    app.kubernetes.io/name: retool-temporal
    app.kubernetes.io/instance: retool
    app.kubernetes.io/component: web
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: retool-temporal
      app.kubernetes.io/instance: retool
      app.kubernetes.io/component: web
  template:
    metadata:
      labels:
        app.kubernetes.io/name: retool-temporal
        app.kubernetes.io/instance: retool
        app.kubernetes.io/component: web
    spec:
      
      volumes:
        - name: retool-temporal-web-config
          configMap:
            name: retool-temporal-web-config
      containers:
        - name: retool-temporal-web
          image: "temporalio/ui:latest"
          imagePullPolicy: IfNotPresent
          env:
            - name: TEMPORAL_ADDRESS
              value: "retool-temporal-frontend:7233"
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          resources:
            limits:
              cpu: 100m
              memory: 128Mi
---
apiVersion: v1
kind: Service
metadata:
  name: retool-temporal-web
  labels:
    app.kubernetes.io/name: retool-temporal
    app.kubernetes.io/instance: retool
    app.kubernetes.io/component: web
spec:
  type: ClusterIP 
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
      name: http

  selector:
    app.kubernetes.io/name: retool-temporal
    app.kubernetes.io/instance: retool
    app.kubernetes.io/component: web
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: retool-temporal-admintools
  labels:
    app.kubernetes.io/name: retool-temporal
    app.kubernetes.io/instance: retool
    app.kubernetes.io/component: admintools
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: retool-temporal
      app.kubernetes.io/instance: retool
      app.kubernetes.io/component: admintools
  template:
    metadata:
      labels:
        app.kubernetes.io/name: retool-temporal
        app.kubernetes.io/instance: retool
        app.kubernetes.io/component: admintools
    spec:
      
      containers:
        - name: admin-tools
          image: "temporalio/admin-tools:1.18.5"
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 22
              protocol: TCP
          env:
            - name: TEMPORAL_CLI_ADDRESS
              value: retool-temporal-frontend:7233
          livenessProbe:
              exec:
                command:
                - ls
                - /
              initialDelaySeconds: 5
              periodSeconds: 5
          resources:
            limits:
              cpu: 100m
              memory: 128Mi
---
apiVersion: v1
kind: Service
metadata:
  name: retool-temporal-admintools
  labels:
    app.kubernetes.io/name: retool-temporal
    app.kubernetes.io/instance: retool
    app.kubernetes.io/component: admintools
spec:
  type: ClusterIP 
  ports:
    - port: 22
      targetPort: 22
      protocol: TCP
      name: ssh

  selector:
    app.kubernetes.io/name: retool-temporal
    app.kubernetes.io/instance: retool
    app.kubernetes.io/component: admintools