apiVersion: v1
kind: Service
metadata:
  name: retool-temporal-matching-headless
  labels:
    app.kubernetes.io/name: retool-temporal
    app.kubernetes.io/instance: retool
    app.kubernetes.io/component: matching
    app.kubernetes.io/headless: 'true'

  annotations:
    # Use this annotation in addition to the actual field below because the
    # annotation will stop being respected soon but the field is broken in
    # some versions of Kubernetes:
    # https://github.com/kubernetes/kubernetes/issues/58662
    service.alpha.kubernetes.io/tolerate-unready-endpoints: "true"
spec:
  type: ClusterIP
  clusterIP: None
  publishNotReadyAddresses: true
  ports:
    - port: 7233
      targetPort: rpc
      protocol: TCP
      name: grpc-rpc
  selector:
    app.kubernetes.io/name: retool-temporal
    app.kubernetes.io/instance: retool
    app.kubernetes.io/component: matching
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: retool-temporal-matching
  labels:
    app.kubernetes.io/name: retool-temporal
    app.kubernetes.io/instance: retool
    app.kubernetes.io/component: matching
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: retool-temporal
      app.kubernetes.io/instance: retool
      app.kubernetes.io/component: matching
  template:
    metadata:
      labels:
        app.kubernetes.io/name: retool-temporal
        app.kubernetes.io/instance: retool
        app.kubernetes.io/component: matching
    spec:
      securityContext:
        fsGroup: 1000 #temporal group
        runAsUser: 1000 #temporal user
      containers:
        - name: retool-temporal-matching
          image: "tryretool/one-offs:retool-temporal-1.1.2"
          imagePullPolicy: IfNotPresent
          env:
            - name: POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: ENABLE_ES
              value: "false"
            - name: SERVICES
              value: matching
            - name: DEFAULT_NAMESPACE
              value: workflows
            - name: DB
              value: postgresql
            - name: DBNAME
              value: "temporal"
            - name: VISIBILITY_DBNAME
              value: "temporal_visibility"
            - name: POSTGRES_HOST
              value: postgres
            - name: POSTGRES_PORT
              value: "5432"
            - name: POSTGRES_USER
              value: "retool_internal_user"
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: retooltemporalsecrets
                  key: postgres_password
            - name: TEMPORAL_CLI_ADDRESS
              value: retool-temporal-frontend:7233
            - name: TEMPORAL_STORE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: retooltemporalsecrets
                  key: postgres_password
            - name: TEMPORAL_VISIBILITY_STORE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: retooltemporalsecrets
                  key: postgres_password
          ports:
            - name: rpc
              containerPort: 7235
              protocol: TCP
          livenessProbe:
             initialDelaySeconds: 150
             tcpSocket:
               port: rpc
          volumeMounts:
            - name: config
              mountPath: /etc/temporal/config/config_template.yaml
              subPath: config_template.yaml
            - name: dynamic-config
              mountPath: /etc/temporal/dynamic_config
          resources:
            limits:
              cpu: 500m
              memory: 1024Mi
            requests:
              cpu: 100m
              memory: 128Mi
      volumes:
        - name: config
          configMap:
            name: "retool-temporal-server-config"
        - name: dynamic-config
          configMap:
            name: "retool-temporal-dynamic-config"
            items:
            - key: dynamic_config.yaml
              path: dynamic_config.yaml