apiVersion: v1
kind: Secret
metadata:
  name: retoolsecrets
type: Opaque
data:
  jwt_secret: {{ random base64 encoded string to sign jwt tokens }}
  encryption_key: {{ random base64 encoded string to encrypt database credentials }}
  postgres_password: {{ random base64 encoded string to set as the internal retool db password }}
  license_key: {{ base64 encoded string of the license key Retool will provide you }}
  google_client_id: {{ google client id encoded in base64 }}
  google_client_secret: {{ google client secret encoded in base64 }}
